version: '3.8'

services:
  laravel:
    build:
      context: ./Gateway/gateway
      dockerfile: ../Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network
    depends_on:
      - mysql

  flask:
    build:
      context: ./Flask/Flask_microservice
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network

  email:
    build:
      context: ./Email/Email_microservice
      dockerfile: ../Dockerfile
    ports:
      - "5001:5000"
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nombre_base
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  app-network:

volumes:
  mysql-data:
